services:
  app:
    image: ghcr.io/alandeveloper/kicks:latest
    restart: unless-stopped
    mem_limit: 192m
    cpus: 0.45
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kicks.rule=Host(`kicks.alandeveloper.com.br`)'
      - 'traefik.http.routers.kicks.entrypoints=web'
      - 'traefik.http.routers.kicks.service=kicks'
      - 'traefik.http.services.kicks.loadbalancer.server.port=80'

networks:
  traefik-network:
    external: true
